pipeline:
  gpio:
    image: dabbertorres/rpi3-gcc
    commands:
      - export CC=rpi3-cc
      - export AR=rpi3-ar
      - export CFLAGS="-Wall -Wextra -O2"
      - make -C gpio
  robit:
    image: dabbertorres/rpi3-gcc
    commands:
      - export CC=rpi3-cc
      - export AR=rpi3-ar
      - export CFLAGS="-Wall -Wextra -O2"
      - make -C robit
  camera:
    image: golang:1.9
    commands:
      - export GOOS=linux
      - export GOARCH=arm
      - export GOARM=7
      - go build robit/camera
  websrv:
    image: golang:1.9
    commands:
      - export GOOS=linux
      - export GOARCH=arm
      - export GOARM=7
      - go build robit/websrv

